[build]
builder = "dockerfile"

[deploy]
startCommand = "node migration/migrate.js && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
